# Website's icon url.
favicon: /favicon.png

# Navigation bar menu links.
menu:
  文章: /zh-cn/archives
  项目: /zh-cn/code
  Music: /zh-cn/categories/Music
  Technology: /zh-cn/categories/Technology
  关于: /zh-cn/about
